### ISSUE TITLE
Whitelist Tokens inConMandatoryCoinBase

### ISSUE THREAD

**Issue by cryptopoly** [commerceblock/ocean#189]
Currently the Whitelist tokens appear in the ConMandatoryCoinBase and may allow users who control the fee wallet to also whitelist people...

<img width="864" alt="Screenshot 2019-08-12 at 12 58 53" src="https://user-images.githubusercontent.com/31970407/62863536-f6379c00-bd00-11e9-933c-1af14840158d.png">

**Comment by nkostoulas** [comment]
I think whitelist transactions no longer pay fees @lawlawlaw @AstryX ?

**Comment by AstryX** [comment]
@nkostoulas They do not. The case where whitelist asset is sent is an edge case where at least 1 satoshi has to be sent for each kyc pubkey whitelisting in 'whitelistkycpubkeys' rpc. If i remember correctly, this is needed for blacklisting so that the 1 satoshi output can be spent or something amongst those lines.

**Comment by nkostoulas** [comment]
ok closing
